version: '3.9'

services:
  explorer:
    image: wavesplatform/explorer
    ports:
      - '3000:8080'
    environment:
      - API_NODE_URL=http://localhost:6869
      - NODE_LIST=http://localhost:6869
    networks:
      - common

  waves_node:
    image: wavesplatform/waves-private-node
    ports:
      - '6869:6869'
      - '6881:6881'
    networks:
      - common
    volumes:
      - ./waves-node-config/waves.conf.my:/etc/waves/waves.conf



networks:
  common:
    driver: bridge
